### PR TITLE
Band meter based on the WTF number.

### PR DESCRIPTION
**Pull request by ardugnome**
Added a band meter based on the WTF numbers and disabled certificate signing.

### CODE REVIEW

**Comment by ken5m1th** [comment]
I just started using this app today. I think this is a fantastic addition.

**Comment by Efpophis** [comment]
Man, I haven't worked on this project for a long time. This looks good tho. Let me make sure I can build it and everything and I'll do the merge.

Thanks for you contribution!

**Comment by ardugnome** [comment]
> 

No rush, I think the power supply voltage could be a user saved setting just like the COM port, but I was unable to do it for some reason.  I probably messed up the progress bars, they may not line up correctly to represent the actual power in watts.
Please check the code thoroughly before releasing it, in case I made mistakes. 

I am working on an Arduino Meter based on your work but don't really know my way around the code, so it's a slow go.

Merry Christmas and Happy New Year! Thanks a million for writing this.

**Comment by celegroz** [comment]
Found this while searching in vain to find the discontinued LDG M-1000 meter. Not sure I can help much with the LDG interface code, but would be willing to help with the Arduino meter. Lots of cool oled diplays out now!

**Comment by Efpophis** [comment]
Hey guys, I thank you so much for the offers to help. Things have been crazy around here lately and I just haven't had time to keep this project going. That said, feel free to submit pull requests or make your own fork to mess with/distribute/whatever. I'll get around to maintaining this at some point.

**Pull request merged**
